//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;

namespace ZomboidBackupManager.Properties
{
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        public static Image SwitchIconOn { get; internal set; }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZomboidBackupManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThumbnailPlaceholder
        {
            get
            {
                object obj = ResourceManager.GetObject("ThumbnailPlaceholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon PZBackupManagerIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("PZBackupManagerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Bitmap IconImage
        {
            get
            {
                object obj = ResourceManager.GetObject("IconImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DoneButtonSelectMulti
        {
            get
            {
                object obj = ResourceManager.GetObject("DoneButtonSelectMulti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ConnectSpiffo
        {
            get
            {
                object obj = ResourceManager.GetObject("ConnectSpiffo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RadiowaveIconImage
        {
            get
            {
                object obj = ResourceManager.GetObject("RadiowaveIconImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap CheckmarkFilled
        {
            get
            {
                object obj = ResourceManager.GetObject("CheckmarkFilled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Checkmark
        {
            get
            {
                object obj = ResourceManager.GetObject("Checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SquareWithPlusIconImage
        {
            get
            {
                object obj = ResourceManager.GetObject("SquareWithPlusIconImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StarCharButton
        {
            get
            {
                object obj = ResourceManager.GetObject("StarCharButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RedBar
        {
            get
            {
                object obj = ResourceManager.GetObject("RedBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InfoIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("InfoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap FolderIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("FolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap CheckmarkIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("CheckmarkIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DocumentIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("DocumentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SpiffoHighlightsWithBackground
        {
            get
            {
                object obj = ResourceManager.GetObject("SpiffoHighlightsWithBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SteamLogo128
        {
            get
            {
                object obj = ResourceManager.GetObject("SteamLogo128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap GitHubLogo128
        {
            get
            {
                object obj = ResourceManager.GetObject("GitHubLogo128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Gear2Color_BW
        {
            get
            {
                object obj = ResourceManager.GetObject("Gear2Color_BW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap LoadIconCCW_B
        {
            get
            {
                object obj = ResourceManager.GetObject("LoadIconCCW_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Checkmark24
        {
            get
            {
                object obj = ResourceManager.GetObject("Checkmark24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap CheckmarkFilled24
        {
            get
            {
                object obj = ResourceManager.GetObject("CheckmarkFilled24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowRightIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowRightIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowLeftIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowLeftIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowLeftDownIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowLeftDownIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ArrowRightUpIcon
        {
            get
            {
                object obj = ResourceManager.GetObject("ArrowRightUpIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Image PZBackupManagerLogo
        {
            get
            {
                object obj = ResourceManager.GetObject("PZBackupManagerLogo", resourceCulture);
                return ((System.Drawing.Image)(obj));
            }
        }
    }
}