name: Build and Release

on:
  push:
    tags:
      - "v*"  # Löst den Workflow aus, wenn ein Tag erstellt wird, z. B. v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -r win-x64 --self-contained true --property:PublishDir=publish

      - name: Create Build Directory
        run: New-Item -ItemType Directory -Path Build -Force

      - name: Create Zip Archive
        run: |
          Compress-Archive -Path publish\* -DestinationPath Build/PZBackupManager.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PZBackupManager
          path: Build/PZBackupManager.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Build/PZBackupManager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
